version: '3.8'

services:
  app:
    image: baha423/kaddem-app:latest  # Assurez-vous que l'image Docker est déjà buildée et poussée vers Docker Hub
    ports:
      - "8089:8089"  # Port de votre application Spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kaddemdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=azerty
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: kaddemdb
    ports:
      - "3306:3306"
