pipeline {
    agent any
    stages {
        stage('Git') {
            steps {
                checkout scm
            }
        }
        stage('Compile') {
            steps {
                dir('backend') {
                    sh 'chmod +x mvnw'
                    sh './mvnw compile'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('backend') {
                    withSonarQubeEnv('SonarQube-Serveur') {
                        sh './mvnw sonar:sonar'
                    }
                }
            }
        }
    }
}
