pipeline {
    agent any
    stages {
        stage('Git') {
            steps {
                checkout scm
            }
        }
        stage('Display Branch Name') {
            steps {
                script {
                    echo "Current branch: ${env.BRANCH_NAME}"
                }
            }
        }
        stage('Compile') {
            steps {
                dir('backend') {
                    sh 'chmod +x mvnw'
                    sh './mvnw compile'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('backend') {
                    withSonarQubeEnv('SonarQube-Serveur') {
                        sh "./mvnw sonar:sonar -Dsonar.branch.name=${env.BRANCH_NAME}"
                    }
                }
            }
        }
    }
}
