server:
  port: 8050

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EquipeDB
    username: hend
    password: hend
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  config:
    projet-url: http://localhost:8222/projet