server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ProjetMicroservice
          uri: lb:http://PROJETMICROSERVICE
          predicates:
            - Path=/projet/**
        - id: EquipeMicroservice
          uri: lb:http://EQUIPEMICROSERVICE
          predicates:
            - Path=/equipe/**