server:
  port: 8887
spring:
  data:
    mongodb:
      username: hend
      password: hend
      host: mongodb
      port: 27017
      database: ProjetDB
      authentication-database: admin
eureka:
  instance:
    hostname: 192.168.33.10
  client:
    service-url:
      defaultZone: http://192.168.33.10:8761/eureka
application:
  config:
    equipe-url: http://192.168.33.10:8222/equipe
