server:
  port: 8055
spring:
  data:
    mongodb:
      username: hend
      password: hend
      host: 192.168.33.10
      port: 27017
      database: ProjetDB
      authentication-database: admin

application:
  config:
    equipe-url: http://192.168.33.10:8222/equipe
