server:
  port: 8055
spring:
  data:
    mongodb:
      username: hend
      password: hend
      host: localhost
      port: 27017
      database: ProjetDB
      authentication-database: admin

application:
  config:
    equipe-url: http://localhost:8222/equipe
