services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hend
      - MONGO_INITDB_ROOT_PASSWORD=hend
    networks:
      - microservices-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - mongo_data:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=hend
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hend
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - microservices-net

  sonarqube:
    image: sonarqube:lts
    container_name: sonar
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres_db/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - microservices-net
    depends_on:
      - postgres_db

  nexus:
    image: sonatype/nexus3
    container_name: nexuss
    ports:
      - 8082:8081
    volumes:
      - nexus_data:/nexus-data
    networks:
      - microservices-net

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=EquipeDB
      - MYSQL_USER=hend
      - MYSQL_PASSWORD=hend
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql_db
      - PMA_USER=hend
      - PMA_PASSWORD=hend
    ports:
      - 8083:80
    depends_on:
      - mysql
    networks:
      - microservices-net

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  frontend:
    image: frontendimage
    container_name: frontend_container
    ports:
      - 8088:8088
    networks:
      - microservices-net
    volumes:
      - frontend_data:/app/data # Adjust this path based on your needs
    depends_on:
      - eureka

  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka_server
    ports:
      - 8761:8761
    networks:
      - microservices-net

  projetmicroservie:
    image: projetmicroservieimage
    container_name: projet_microservice_container
    ports:
      - 8086:8086
    networks:
      - microservices-net
    volumes:
      - projetmicroservie_data:/data # Adjust this path based on your needs
    depends_on:
      - eureka

  equipemicroservie:
    image: equipemicroservieimage
    container_name: equipe_microservice_container
    ports:
      - 8084:8084
    networks:
      - microservices-net
    volumes:
      - equipemicroservie_data:/data # Adjust this path based on your needs
    depends_on:
      - eureka

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
  mysql_data:
  postgres_data:
  frontend_data: # Add a volume for frontend
  projetmicroservie_data: # Add a volume for projetmicroservie
  equipemicroservie_data: # Add a volume for equipemicroservie
